
# defaults
#INVOICE_API_PREFIX = '/invoice'
INVOICE_API_PREFIX = ''
EMAIL_NEW_INVOICE_PATH = INVOICE_API_PREFIX + '/emailNewInvoice'
GET_ALL_INVOICES = INVOICE_API_PREFIX + '/getAllInvoices'
EMAIL_INVOICE_PATH = INVOICE_API_PREFIX + '/emailInvoice'
